package com.dean.iso8583.core.emv.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Developer Note:
 * Registry of well-known EMV tag identifiers as defined in:
 * <ul>
 *     <li>EMV Book 3 (Application Specification)</li>
 *     <li>EMV Book 4 (Other Interfaces)</li>
 *     <li>EMVCo Payment Tokenization Specification</li>
 * </ul>
 *
 * These tags appear primarily inside DE 55 (ICC System Related Data) of an
 * ISO 8583 authorization request (0200) and response (0210) for chip card and
 * contactless transactions (NFC / CTLS).
 *
 *
 * <ul><br>
 *     Enterprise Relevance:
 *     <li>ARQC (9F26) cryptogram validation is required before approving any chip-initiated transaction — missing or tampered values must trigger decline.</li>
 *     <li>ATC (9F36) monotonically increases with every chip transaction; a decreasing or replayed ATC is a strong fraud signal and MUST be rejected.</li>
 *     <li>Issuer Application Data (9F10) is institution-specific and carries cryptographic counters used for offline PIN verification replay detection.</li>
 * </ul>
 */
@Getter
@AllArgsConstructor
public enum EmvTagName {

    // ─── Cardholder ──────────────────────────────────────────────────────────

    /** 5F20 – Cardholder Name as encoded on the card */
    CARDHOLDER_NAME("5F20", "Cardholder Name"),

    /** 5F24 – Application Expiration Date (YYMMDD) */
    APPLICATION_EXPIRY_DATE("5F24", "Application Expiry Date"),

    /** 5F25 – Application Effective Date (YYMMDD) */
    APPLICATION_EFFECTIVE_DATE("5F25", "Application Effective Date"),

    /** 5F28 – Issuer Country Code (ISO 3166-1 numeric) */
    ISSUER_COUNTRY_CODE("5F28", "Issuer Country Code"),

    /** 5F2A – Transaction Currency Code (ISO 4217 numeric) */
    TRANSACTION_CURRENCY_CODE("5F2A", "Transaction Currency Code"),

    /** 5F30 – Service Code */
    SERVICE_CODE("5F30", "Service Code"),

    /** 5F34 – Application Primary Account Number Sequence Number */
    PAN_SEQUENCE_NUMBER("5F34", "PAN Sequence Number"),

    // ─── Transaction Context ─────────────────────────────────────────────────

    /** 9A – Transaction Date (YYMMDD) */
    TRANSACTION_DATE("9A", "Transaction Date"),

    /** 9C – Transaction Type (e.g. 00=Purchase, 01=Cash) */
    TRANSACTION_TYPE("9C", "Transaction Type"),

    /** 9F02 – Authorisation Amount (n12, implicit 2 decimal places) */
    AMOUNT_AUTHORISED("9F02", "Amount, Authorised (Numeric)"),

    /** 9F03 – Secondary (Cashback) Amount */
    AMOUNT_OTHER("9F03", "Amount, Other (Numeric)"),

    /** 9F21 – Transaction Time (HHMMSS) */
    TRANSACTION_TIME("9F21", "Transaction Time"),

    /** 9F37 – Unpredictable Number (anti-replay nonce generated by terminal) */
    UNPREDICTABLE_NUMBER("9F37", "Unpredictable Number"),

    // ─── Cryptographic / Authentication ──────────────────────────────────────

    /**
     * 9F26 – Authorisation Request Cryptogram (ARQC).
     *<ul><br>
     * Developer Note:
     *     <li>This is the primary on-chip MAC that the issuer MUST verify.</li>
     *     <li>An 8-byte value derived from transaction data + card master key.</li>
     *     <li>Incorrect ARQC = potential skimmed/cloned card — must decline.</li>
     *</ul>
     *
     */
    ARQC("9F26", "Application Request Cryptogram (ARQC)"),

    /**
     * 9F10 – Issuer Application Data (IAD).
     *<ul><br>
     * Developer Note:
     *     <li>Proprietary issuer data embedded by the chip firmware.</li>
     *     <li>Contains offline CVR (Card Verification Result) and key derivation</li>
     *     <li>counters. The issuer host must parse this field during ARQC validation.</li>
     *</ul>
     */
    ISSUER_APPLICATION_DATA("9F10", "Issuer Application Data"),

    /**
     * 9F36 – Application Transaction Counter (ATC).
     *<ul><br>
     * Developer Note:
     *
     * <li>Monotonically increasing 2-byte counter maintained by the chip.</li>
     * <li>The issuer must record the last seen ATC per card and REJECT any</li>
     * <li>authorization where ATC ≤ last-seen (replay attack detection).</li>
     * </ul>
     */
    APPLICATION_TRANSACTION_COUNTER("9F36", "Application Transaction Counter (ATC)"),

    /** 9F27 – Cryptogram Information Data (CID) — indicates ARQC, TC, or AAC */
    CRYPTOGRAM_INFORMATION_DATA("9F27", "Cryptogram Information Data"),

    /** 9F45 – Data Authentication Code */
    DATA_AUTHENTICATION_CODE("9F45", "Data Authentication Code"),

    // ─── Terminal ────────────────────────────────────────────────────────────

    /** 9F1A – Terminal Country Code (ISO 3166-1 numeric) */
    TERMINAL_COUNTRY_CODE("9F1A", "Terminal Country Code"),

    /** 9F33 – Terminal Capabilities */
    TERMINAL_CAPABILITIES("9F33", "Terminal Capabilities"),

    /** 9F34 – Cardholder Verification Method (CVM) Results */
    CVM_RESULTS("9F34", "Cardholder Verification Method Results"),

    /** 9F35 – Terminal Type */
    TERMINAL_TYPE("9F35", "Terminal Type"),

    /** 9F40 – Additional Terminal Capabilities */
    ADDITIONAL_TERMINAL_CAPABILITIES("9F40", "Additional Terminal Capabilities"),

    /** 9F41 – Transaction Sequence Counter */
    TRANSACTION_SEQUENCE_COUNTER("9F41", "Transaction Sequence Counter"),

    // ─── Application ─────────────────────────────────────────────────────────

    /** 4F – Application Identifier (AID) */
    APPLICATION_IDENTIFIER("4F", "Application Identifier"),

    /** 50 – Application Label */
    APPLICATION_LABEL("50", "Application Label"),

    /** 82 – Application Interchange Profile (AIP) */
    APPLICATION_INTERCHANGE_PROFILE("82", "Application Interchange Profile"),

    /** 84 – Dedicated File (DF) Name */
    DF_NAME("84", "Dedicated File Name"),

    /** 8A – Authorisation Response Code (from issuer, placed back by terminal) */
    AUTHORISATION_RESPONSE_CODE("8A", "Authorisation Response Code"),

    /** 8E – Cardholder Verification Method (CVM) List */
    CVM_LIST("8E", "Cardholder Verification Method List"),

    /** 9F07 – Application Usage Control */
    APPLICATION_USAGE_CONTROL("9F07", "Application Usage Control"),

    /** 9F08 – Application Version Number (Card) */
    APPLICATION_VERSION_NUMBER("9F08", "Application Version Number"),

    /** 9F09 – Application Version Number (Terminal) */
    APPLICATION_VERSION_NUMBER_TERMINAL("9F09", "Application Version Number (Terminal)"),

    /** 9F0D – Issuer Action Code – Default */
    ISSUER_ACTION_CODE_DEFAULT("9F0D", "Issuer Action Code - Default"),

    /** 9F0E – Issuer Action Code – Denial */
    ISSUER_ACTION_CODE_DENIAL("9F0E", "Issuer Action Code - Denial"),

    /** 9F0F – Issuer Action Code – Online */
    ISSUER_ACTION_CODE_ONLINE("9F0F", "Issuer Action Code - Online"),

    // ─── Contactless / NFC ───────────────────────────────────────────────────

    /** 9F6E – Form Factor Indicator (Contactless) */
    FORM_FACTOR_INDICATOR("9F6E", "Form Factor Indicator"),

    /** 9F6C – Card Transaction Qualifiers (CTQ) for Visa contactless */
    CARD_TRANSACTION_QUALIFIERS("9F6C", "Card Transaction Qualifiers"),

    // ─── Issuer Response ─────────────────────────────────────────────────────

    /** 91 – Issuer Authentication Data (returned in 0210 for ARPC) */
    ISSUER_AUTHENTICATION_DATA("91", "Issuer Authentication Data"),

    /** 71 – Issuer Script Template 1 */
    ISSUER_SCRIPT_TEMPLATE_1("71", "Issuer Script Template 1"),

    /** 72 – Issuer Script Template 2 */
    ISSUER_SCRIPT_TEMPLATE_2("72", "Issuer Script Template 2"),

    /** UNKNOWN – catch-all for proprietary or unrecognised tags */
    UNKNOWN("", "Unknown Tag");

    // ─────────────────────────────────────────────────────────────────────────

    private final String hexTag;
    private final String description;


    /**
     * Resolves a hex tag string (case-insensitive) to its {@link EmvTagName}.<br>
     * <li>Returns {@link #UNKNOWN} for any tag not in the registry.</li>
     *
     * @param tag hex tag identifier, e.g. {@code "9F26"}
     * @return matching enum constant or {@link #UNKNOWN}
     */
    public static EmvTagName fromTag(String tag) {
        if (tag == null || tag.isBlank()) return UNKNOWN;
        String upperTag = tag.toUpperCase();
        for (EmvTagName entry : values()) {
            if (entry.hexTag.equalsIgnoreCase(upperTag)) {
                return entry;
            }
        }
        return UNKNOWN;
    }
}
